import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
// The browser and import/export tools share the same reconstruction code.
const source=fs.readFileSync('scripts/database/content.ts','utf8').replace(/^export /gm,'');
const tempDir=path.resolve('work/browser-build');fs.mkdirSync(tempDir,{recursive:true});
fs.writeFileSync(path.join(tempDir,'content.ts'),source);
execFileSync(process.execPath,[path.resolve('node_modules/typescript/bin/tsc'),path.join(tempDir,'content.ts'),'--ignoreConfig','--target','ES2021','--module','es2020','--moduleDetection','legacy','--skipLibCheck','--outDir',tempDir],{stdio:'inherit'});
const compiled=fs.readFileSync(path.join(tempDir,'content.js'),'utf8');
fs.writeFileSync('docs/content-adapter.js','// Generated by npm run build:browser; edit scripts/database/content.ts.\n(()=>{\n'+compiled+'\nwindow.atlasContent={tables,reconstruct};\n})();\n');
fs.unlinkSync(path.join(tempDir,'content.ts'));fs.unlinkSync(path.join(tempDir,'content.js'));
